In [5]:
import os

In [3]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("MyApp") \
    .master("local[*]") \
    .getOrCreate()

In [6]:
print("Master:", spark.sparkContext.master)
print("Default Parallelism:", spark.sparkContext.defaultParallelism)
print("CPU Cores Available:", os.cpu_count())

Master: local[*]
Default Parallelism: 16
CPU Cores Available: 16

In [7]:
rdd = spark.sparkContext.parallelize(range(1000))
print(rdd.getNumPartitions())

16

In [8]:
for k, v in spark.sparkContext.getConf().getAll():
    print(f"{k} = {v}")

spark.app.id = local-1780255268393
spark.rdd.compress = True
spark.hadoop.fs.s3a.vectored.read.min.seek.size = 128K
spark.driver.host = Gaurav
spark.executor.extraJavaOptions = -Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-modules=jdk.incubator.vector --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false -Dio.netty.tryReflectionSetAccessible=true
spark.sql.artifact.isolation.enabled = false
spark.master = local[*]
spark.app.submitTime = 1780255264474
spark.driver.port = 64362
spark.app.name = MyApp
spark.executor.id = driver
spark.submit.pyFiles =
spark.driver.extraJavaOptions = -Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-modules=jdk.incubator.vector --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false -Dio.netty.tryReflectionSetAccessible=true
spark.hadoop.fs.s3a.vectored.read.max.merged.size = 2M
spark.submit.deployMode = client
spark.app.startTime = 1780255266990
spark.serializer.objectStreamReset = 100
spark.ui.showConsoleProgress = true

In [13]:
import os

print("Spark Version:", spark.version)
print("Master:", spark.sparkContext.master)
print("App Name:", spark.sparkContext.appName)
print("Default Parallelism:", spark.sparkContext.defaultParallelism)
print("CPU Threads:", os.cpu_count())
print("Driver Memory:", spark.conf.get("spark.driver.memory", "Not Set"))
print("Executor Memory:", spark.conf.get("spark.executor.memory", "Not Set"))
print("Shuffle Partitions:", spark.conf.get("spark.sql.shuffle.partitions"))
print("AQE Enabled:", spark.conf.get("spark.sql.adaptive.enabled"))
print("Spark UI:", spark.sparkContext.uiWebUrl)

Spark Version: 4.0.0
Master: local[*]
App Name: MyApp
Default Parallelism: 16
CPU Threads: 16
Driver Memory: Not Set
Executor Memory: Not Set
Shuffle Partitions: 200
AQE Enabled: true
Spark UI: http://Gaurav:4040

In [16]:
df = spark.range(1000000)

print("Partitions:", df.rdd.getNumPartitions())

Partitions: 16

In [ ]:
df2 = spark.range(1000000).repartition(32)

print(df2.rdd.getNumPartitions())

In [ ]:
spark.stop()

In [ ]:
# import pandas as pd

# p_df = pd.read_parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Projects\Project 1\My Fintech project\Output\Gold\dim_accounts\part-00000-d71a995c-f00e-448a-bcf2-dd3e614f2a04-c000.snappy.parquet", engine="pyarrow")

# p_df.head(5)

:

In [ ]:
# from pyspark.sql import SparkSession

# spark = SparkSession.builder.appName("read_parquet").getOrCreate()

# df = spark.read.parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Project 1\My Fintech project\Output\Gold\fact_payments\part-00000-5300ef0f-643a-458e-9c45-ff7d6abd3bbe-c000.snappy.parquet")

# df.show()

:

In [ ]:
# df1 = spark.read.parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Project 1\My Fintech project\Output\Silver\Accounts\part-00000-98fe93b5-6ec2-4f56-9bc7-f33e7d2c350d-c000.snappy.parquet")

# df1.show()

+---------+----------+-----------+-------+----------+---------------+-------------+-----------+---------------+-----------+
|AccountID|CustomerID|AccountType|Balance|  OpenDate|AccountAgeYears|AccountStatus|AccountTier|MonthlyInterest|IsHighValue|
+---------+----------+-----------+-------+----------+---------------+-------------+-----------+---------------+-----------+
|     1001|         1|    Savings|10000.0|2023-01-20|            3.0|      Premium|     Bronze|          16.67|      false|
|     1002|         2|   Checking| 5000.0|2023-02-15|           2.93|     Standard|      Basic|           8.33|      false|
|     1003|         3|    Savings| 7500.0|2023-03-10|           2.86|     Standard|      Basic|          12.50|      false|
|     1004|         4|   Checking| 2000.0|2023-04-05|           2.79|     Standard|      Basic|           3.33|      false|
|     1005|         5|    Savings|12000.0|2023-05-12|           2.69|      Premium|     Bronze|          20.00|      false|
|     1006|         6|    Savings| 8200.0|2023-06-20|           2.58|     Standard|      Basic|          13.67|      false|
|     1007|         7|   Checking| 4500.0|2023-07-14|           2.52|     Standard|      Basic|           7.50|      false|
|     1008|         8|    Savings| 9600.0|2023-08-22|           2.41|     Standard|      Basic|          16.00|      false|
|     1009|         9|   Checking| 3300.0|2023-09-18|           2.34|     Standard|      Basic|           5.50|      false|
|     1010|        10|    Savings|10300.0|2023-10-25|           2.24|      Premium|     Bronze|          17.17|      false|
|     1011|        11|   Checking| 5000.0|2023-11-05|           2.21|     Standard|      Basic|           8.33|      false|
|     1012|        12|    Savings| 7800.0|2023-12-10|           2.11|     Standard|      Basic|          13.00|      false|
|     1013|        13|    Savings| 6800.0|2024-01-14|           2.02|     Standard|      Basic|          11.33|      false|
|     1014|        14|   Checking| 4500.0|2024-02-20|           1.91|     Standard|      Basic|           7.50|      false|
|     1015|        15|    Savings| 8700.0|2024-03-11|           1.86|     Standard|      Basic|          14.50|      false|
|     1016|        16|    Savings| 5200.0|2024-04-16|           1.76|     Standard|      Basic|           8.67|      false|
|     1017|        17|   Checking| 3200.0|2024-05-21|           1.66|     Standard|      Basic|           5.33|      false|
|     1018|        18|    Savings| 9400.0|2024-06-25|           1.57|     Standard|      Basic|          15.67|      false|
|     1019|        19|   Checking| 7100.0|2024-07-30|           1.47|     Standard|      Basic|          11.83|      false|
|     1020|        20|    Savings| 6300.0|2024-08-05|           1.46|     Standard|      Basic|          10.50|      false|
+---------+----------+-----------+-------+----------+---------------+-------------+-----------+---------------+-----------+
only showing top 20 rows

In [ ]:
# import pandas as pd

# df = pd.read_csv(r"D:\GAURAV\My Learnings\Spark Tutorials Youtube\Practice_file.csv")
# df.head()

,Cust ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Date of Birth,SSN,...,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Total Revenue,Year,Month,Delivery Days
0,C-973342,Mr.,Nickolas,V,Lara,M,nickolas.lara@hotmail.com,Elliott Lara,1992-03-24,419-67-3843,...,M,2015-10-17,VG-022_4229433687_AK22,2015-10-17,22,118.209,2600.598,2015,10,0
1,C-880500,Mrs.,Lahoma,S,Lachance,F,lahoma.lachance@microsoft.com,Marco Lachance,1990-02-05,534-71-6211,...,H,2016-11-12,BV-002_4268632909_AK110,2016-11-20,71,41.327,2934.217,2016,11,8
2,C-439016,Dr.,Franklin,M,Rutter,M,franklin.rutter@gmail.com,Abel Rutter,1996-02-11,352-08-1915,...,L,2018-07-24,CT-003_4330535106_AK71,2018-07-24,43,46.592,2003.456,2018,7,0
3,C-635735,Ms.,Cathryn,F,Durham,F,cathryn.durham@shell.com,Antwan Durham,1971-02-05,552-99-1456,...,L,2016-02-03,CR-003_4240325969_AK1,2016-02-03,51,152.243,7764.393,2016,2,0
4,C-213274,Ms.,Verda,K,Oswalt,F,verda.oswalt@gmail.com,Demetrius Oswalt,1977-10-09,657-36-0554,...,H,2016-01-24,BF-002_4239328407_AK70,2016-01-24,71,207.246,14714.466,2016,1,0

In [ ]:
# df.to_parquet("D:\GAURAV\My Learnings\Spark Tutorials Youtube\Practice_file_parquet.parquet", engine= "pyarrow")

<>:1: SyntaxWarning: "\G" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\G"? A raw string is also an option.
<>:1: SyntaxWarning: "\G" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\G"? A raw string is also an option.
C:\Users\91968\AppData\Local\Temp\ipykernel_23400\1152821086.py:1: SyntaxWarning: "\G" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\G"? A raw string is also an option.
  df.to_parquet("D:\GAURAV\My Learnings\Spark Tutorials Youtube\Practice_file_parquet.parquet", engine= "pyarrow")

In [ ]:
# df= pd.read_parquet(r"D:\GAURAV\My Learnings\Spark Tutorials Youtube\Practice_file_parquet.parquet", engine = "pyarrow")
# df.head()

,Cust ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Date of Birth,SSN,...,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Total Revenue,Year,Month,Delivery Days
0,C-973342,Mr.,Nickolas,V,Lara,M,nickolas.lara@hotmail.com,Elliott Lara,1992-03-24,419-67-3843,...,M,2015-10-17,VG-022_4229433687_AK22,2015-10-17,22,118.209,2600.598,2015,10,0
1,C-880500,Mrs.,Lahoma,S,Lachance,F,lahoma.lachance@microsoft.com,Marco Lachance,1990-02-05,534-71-6211,...,H,2016-11-12,BV-002_4268632909_AK110,2016-11-20,71,41.327,2934.217,2016,11,8
2,C-439016,Dr.,Franklin,M,Rutter,M,franklin.rutter@gmail.com,Abel Rutter,1996-02-11,352-08-1915,...,L,2018-07-24,CT-003_4330535106_AK71,2018-07-24,43,46.592,2003.456,2018,7,0
3,C-635735,Ms.,Cathryn,F,Durham,F,cathryn.durham@shell.com,Antwan Durham,1971-02-05,552-99-1456,...,L,2016-02-03,CR-003_4240325969_AK1,2016-02-03,51,152.243,7764.393,2016,2,0
4,C-213274,Ms.,Verda,K,Oswalt,F,verda.oswalt@gmail.com,Demetrius Oswalt,1977-10-09,657-36-0554,...,H,2016-01-24,BF-002_4239328407_AK70,2016-01-24,71,207.246,14714.466,2016,1,0

In [2]:
import pandas as pd

C_1 = pd.read_parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Projects\Azure DB Project - Ansh\My ETL Project\Data\customer_first.parquet", engine="pyarrow")

C_1.head(5)

,customer_id,first_name,last_name,email,city,state
0,C00001,Emily,Mooney,rushjeff@ryan.org,Johnsonmouth,MS
1,C00002,Andrea,Sellers,mccoykiara@kelly.com,Stephenfort,WY
2,C00003,Craig,Hayes,rebeccamiller@yahoo.com,South Stephenshire,LA
3,C00004,Bryan,Scott,lawrence05@campbell.info,Chrisland,ND
4,C00005,Sean,Vasquez,carrie45@yahoo.com,East Dennistown,RI

In [4]:
import pandas as pd

C_2 = pd.read_parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Projects\Azure DB Project - Ansh\My ETL Project\Data\customers_second.parquet", engine="pyarrow")

C_2.head(5)

,customer_id,first_name,last_name,email,city,state
0,C01991,Sonia,Matthews,craigbarajas@williamson.com,Sylviafort,MS
1,C01992,Andrew,Turner,pcross@hotmail.com,New Anthonybury,MT
2,C01993,Daniel,Flynn,careyjohn@ortiz.com,Port Larrymouth,TN
3,C01994,Nicole,Griffin,barkertaylor@hampton.info,North Ericshire,NJ
4,C01995,Vincent,Long,millerjodi@hotmail.com,Wolffort,FL

In [5]:
import pandas as pd

o_1 = pd.read_parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Projects\Azure DB Project - Ansh\My ETL Project\Data\orders_first.parquet", engine="pyarrow")

o_1.head(5)

  order_id customer_id product_id  order_date  quantity  total_amount
0   O00001      C00710      P0159  2023-03-22         3       2022.87
1   O00002      C00954      P0036  2023-06-30         2       3560.74
2   O00003      C01578      P0427  2023-11-06         3       5903.52
3   O00004      C00962      P0332  2024-02-27         3       4107.99
4   O00005      C00156      P0038  2024-10-13         5       5784.95

In [6]:
import pandas as pd

o_2 = pd.read_parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Projects\Azure DB Project - Ansh\My ETL Project\Data\orders_second.parquet", engine="pyarrow")

o_2.head(5)

  order_id customer_id product_id  order_date  quantity  total_amount
0   O09991      C01696      P0138  2024-07-10         1        452.81
1   O09992      C00203      P0055  2024-11-14         3       2776.17
2   O09993      C00568      P0008  2023-01-04         2       2502.52
3   O09994      C01157      P0160  2023-04-10         2       3084.92
4   O09995      C01824      P0036  2023-01-21         5       8901.85

In [7]:
import pandas as pd

p_1 = pd.read_parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Projects\Azure DB Project - Ansh\My ETL Project\Data\products_first.parquet", engine="pyarrow")

p_1.head(5)

  product_id      product_name  category    brand    price
0      P0001       Clearly Its    Beauty     Nike  1868.54
1      P0002  Production Clear    Beauty    Apple   587.13
2      P0003     Culture Coach      Home   Revlon  1599.24
3      P0004     Movement Part    Sports       LG   651.71
4      P0005         Fact Name  Clothing  Samsung  1861.78

In [8]:
import pandas as pd

p_2 = pd.read_parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Projects\Azure DB Project - Ansh\My ETL Project\Data\products_second.parquet", engine="pyarrow")

p_2.head(5)

  product_id     product_name  category    brand    price
0      P0491        Floor Sit  Clothing       LG  1602.21
1      P0492        A Forward      Home     Nike   121.07
2      P0493          Pass Go      Toys  Samsung   295.70
3      P0494   Personal Stand      Toys    Apple  1913.83
4      P0495  Sister Question      Toys     Sony   561.99

In [9]:
import pandas as pd

r_1 = pd.read_parquet(r"D:\GAURAV\My Learnings\Grow Data Skills DE\Projects\Azure DB Project - Ansh\My ETL Project\Data\regions.parquet", engine="pyarrow")

r_1.head(5)

  region_id region
0       R01   East
1       R02   West
2       R03  North
3       R04  South

In [10]:
combine_c =  pd.concat([C_1,C_2])
combine_o = pd.concat([o_1,o_2])
combine_p = pd.concat([p_1,p_2])

In [12]:
output = 'D:\\GAURAV\\My Learnings\\Grow Data Skills DE\\Projects\\Azure DB Project - Ansh\\My ETL Project - Updated\Data-csv\\customers.csv'
combine_c.to_csv(output)

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\91968\AppData\Local\Temp\ipykernel_4408\4047155633.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  output = 'D:\\GAURAV\\My Learnings\\Grow Data Skills DE\\Projects\\Azure DB Project - Ansh\\My ETL Project - Updated\Data-csv\\customers.csv'

In [13]:
output = 'D:\\GAURAV\\My Learnings\\Grow Data Skills DE\\Projects\\Azure DB Project - Ansh\\My ETL Project - Updated\Data-csv\\orders.csv'
combine_o.to_csv(output)

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\91968\AppData\Local\Temp\ipykernel_4408\3797097488.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  output = 'D:\\GAURAV\\My Learnings\\Grow Data Skills DE\\Projects\\Azure DB Project - Ansh\\My ETL Project - Updated\Data-csv\\orders.csv'

In [14]:
output = 'D:\\GAURAV\\My Learnings\\Grow Data Skills DE\\Projects\\Azure DB Project - Ansh\\My ETL Project - Updated\Data-csv\\products.csv'
combine_p.to_csv(output)

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\91968\AppData\Local\Temp\ipykernel_4408\3186461514.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  output = 'D:\\GAURAV\\My Learnings\\Grow Data Skills DE\\Projects\\Azure DB Project - Ansh\\My ETL Project - Updated\Data-csv\\products.csv'

In [15]:
output = 'D:\\GAURAV\\My Learnings\\Grow Data Skills DE\\Projects\\Azure DB Project - Ansh\\My ETL Project - Updated\Data-csv\\regions.csv'
r_1.to_csv(output)

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\91968\AppData\Local\Temp\ipykernel_4408\2464248735.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  output = 'D:\\GAURAV\\My Learnings\\Grow Data Skills DE\\Projects\\Azure DB Project - Ansh\\My ETL Project - Updated\Data-csv\\regions.csv'

In [ ]:
#